name: omni-vsr
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - pyyaml
  - protobuf>
  - tqdm
  - einops
  - opencv
  - ffmpeg
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip:
      - mediapipe
      - pyctcdecode
      - kenlm
      - editdistance
      - kaggle
      - g2p-en
      - -e .
